dist: jammy
language: ruby
rvm:
  - "3.4"

cache: bundler

## Build all possible jekyll pages for use with link checking.
script:
    - make production

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
  - sudo apt-get update
  - sudo apt-get install -y optipng
